### ISSUE TITLE
Application autoscrolls after bigvideo.js

### ISSUE THREAD

**Issue by 123ndy** [TrySound/skrollr-decks#10]
In "section number two (`#deck-2-video`)" I use a fullscreen video (with bigvideo.js):

in *index.html.erb*
```
<section class="skrollr-deck" id="deck-2-video">
	<div class"row" id="video-row">
		<div class="col-md-12" id="video-container">
		</div>
	</div>
</section>
```

in *application.html.erb*
```
<script>
    $(function() {
        var BV = new $.BigVideo({container: $('#video-container')});
        BV.init();
        BV.show("<%= request.protocol + request.host_with_port + asset_path('video.mp4') %>",{ambient:true});
    });
</script>
```

When I scroll past `#deck-2-video`, the application auto scroll through the rest of the section that is under the section where bigvideo.js is present (`#deck-2-video`) until it hits the bottom of the document.

Any solution to this?

**Comment by TrySound** [comment]
My brain is crashed. Many work :))
Can you create repository with simple non-back-end example?

**Comment by 123ndy** [comment]
Sorry for late reply TrySound. I found that the reason for the autoscrolling was because the bigvideo container was higher than the section container ("skrollr-deck"). I just fixed the height of the bigvideo container and the autoscrolling stopped.

**Comment by TrySound** [comment]
Cool)
I make nice grids. Check it http://github.com/TrySound/patch-layout

**Comment by 123ndy** [comment]
Nice, I will check it out! Keep up the good work :)
