### ISSUE TITLE
Footer after last deck

### ISSUE THREAD

**Issue by alexgordon25** [TrySound/skrollr-decks#11]
I have a footer container after last deck, but when I scroll to bottom where is footer information, the page autoscroll back to last deck. How can I prevent that?

**Comment by TrySound** [comment]
Which version did you try?

**Comment by alexgordon25** [comment]
skrollr-decks 0.2.2

**Comment by TrySound** [comment]
For now it's 1.0.4
I rewrite all code. I like how it works now.

**Comment by alexgordon25** [comment]
Ok, let me give it a try to the new version.

**Comment by alexgordon25** [comment]
Uncaught TypeError: Cannot read property 'offsetHeight' of undefined 
resizeDecks
skrollr.decks.js:198

**Comment by alexgordon25** [comment]
Now it works. skrollr-decks-init have to be on body prefered or a main wrapper container. 
Autoscroll on footer is fixed. thanks

One feature missing on new version. On nav items there is no active class changing during when scrolling. (.skrollr-decks-achor-active)

**Comment by TrySound** [comment]
On body. I don't use custom navigation in new version. For this you can use method animateTo(anchor, callback).

**Comment by TrySound** [comment]
Maybe in future I will make custom links like data-skrollr-deck-anchor
