### ISSUE TITLE
Change height of .skrollr-deck

### ISSUE THREAD

**Issue by 123ndy** [TrySound/skrollr-decks#12]
Is there a way of changing the min-height of some of the decks, but not all?

I tried with CSS, but that didn't work out.

**Comment by TrySound** [comment]
No, decks must be min screen height. It's main logic of this.

**Comment by 123ndy** [comment]
Ok, I am trying to "make a slide over another slide" (like the first slide on this page: http://www.gogoro.com), how would you do that with skrollr-deck?

**Comment by TrySound** [comment]
Do you wanna do parallax effect?

**Comment by 123ndy** [comment]
In a way, or more like having a deck over another deck; a deck behind the overlaying deck that does not slide before the deck above is slide away (like in the first slide in the link above). How could I do this?

**Comment by TrySound** [comment]
You can make fullscreen `position: fixed` element (outside #skrollr-body). And add empty deck to you page. Then by `position: relative` and `z-index` change overlaying 

P.S.: I'll update it now. Normalized over screen height decks.

**Comment by TrySound** [comment]
And you can use skrollr features with css transformations

**Comment by 123ndy** [comment]
Ok, nice. But this would only work for the first slide on the page? If I would like to make this effect on slide 4 on the page, then I would have to implement it in another way?

**Comment by TrySound** [comment]
skrollr features with css transformations and data-anchor-target

**Comment by TrySound** [comment]
Make example in demo for you

**Comment by 123ndy** [comment]
Hi TrySound, 

Sorry, I haven't replied on his before! Thanks for the update, now I can adjust the height of a section and by doing this I placed two fullscreen divs within one section and then solved the challenge by let the first div slide above the latter. And you were totally right about using skrollr functions to do this in the middle of the page! I really appreciated all the help!

**Comment by TrySound** [comment]
You're welcome, Sigurd!
