### ISSUE TITLE
resizeDecks causing jump to another deck

### ISSUE THREAD

**Issue by jrit** [TrySound/skrollr-decks#22]
If I'm on maybe the 5th deck and then use `resizeDecks`, after the resize the page is scrolling up the the prior deck. I found this could be prevented by adding this to the end of `resizeDecks`. This is similar to the current handling of `skrollr.addEvent(window, 'load resize', function () {` so I'm not aware of any downside to adding it.

```js
if(currentDeck) {
	animateTo('#' + currentDeck.id, true);
}
```

**Comment by TrySound** [comment]
Hi @jrit! You can make Pull Request and I will check it.
